.phony: all clean 
.default: all

all: bin/$(PROJECT).dll

bin/$(PROJECT).dll :  
	@banner $(PROJECT)
	@make clean
	@-mkdir bin
	@$(BUILD)

clean:
	@echo Cleaning $(PROJECT)
	@rm -rf bin/$(PROJECT).dll	

